@api=http://localhost:5000

###
POST {{api}}/users
Content-Type: application/json

{
    "name":"Kolya",
    "email": "kolya924@gmail.com",
    "password": "12345",
    "icon":""
}
###
POST {{api}}/auth/register
Content-Type: application/json

{
    "name":"TestUser",
    "email": "newEmail123@gmail.com",
    "password": "securePassword",
    "icon":""
}
###